version: "3.9"

services:
  app:
    build:
      context: .  # Build context is the current directory
      args:
        DEV: "true"  # Pass the build argument with a key-value pair
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# Define the volume
volumes:
  dev-db-data:




# version: "3.9"

# services:
#   app:
#     build:
#       context: .  # Add the build context here, assuming your Dockerfile is in the current directory
#       args:
#         DEV=true
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app
#     command: 
#       sh -C "python manage.py runserver 0.0.0.0:8000"  # Directly running the command without the need for `sh -C`
